name: Main CD Pipeline
# This is the main CD pipeline for the project. It is triggered by a push to the main branch.
# It builds the frontend and backend images and pushes them to Docker Hub.
# The frontend and backend images are then deployed to the production environment.
# The production environment is a Kubernetes cluster running in AWS.
# The frontend and backend images are deployed to the production environment using a Helm chart.
# The Helm chart is stored in the ci-cd-node-app repository.
# The Helm chart is deployed to the production environment using a Helm CLI.
# The Helm CLI is installed in the production environment using a Helm CLI image.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-app:frontend ./frontend

      - name: Build backend image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-app:backend ./backend

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-app:frontend

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-app:backend
